### ISSUE TITLE
chore: alter the proof size in the rln-relay spec

### ISSUE THREAD

**Issue by rymnc** [vacp2p/rfc-index#43]
ref issue: https://github.com/waku-org/nwaku/issues/2757

Identified mismatch between implementation and the spec. we can alter the spec to note that the proof size is 256 bytes (uncompressed), and 128 compressed.

cc: @jimstir @kaiserd 

thanks for the report @AlejandroCabeza

**Comment by jimstir** [comment]
Opened a pr located [here](https://github.com/vacp2p/rfc-index/pull/44)
